# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-02 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='latitude',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='article',
            name='longtitude',
            field=models.CharField(max_length=40),
        ),
    ]
