# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-04 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_auto_20170503_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='detail_description',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
