# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-02 22:53
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_auto_20170502_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='coordinate',
            field=django.contrib.gis.db.models.fields.PointField(default=[-157.971384084284, 21.3834940546563], srid=4326),
            preserve_default=False,
        ),
    ]
