# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-02 22:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_article_coordinate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='coordinate',
        ),
    ]
