# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-02 23:02
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_remove_article_coordinate'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='coordinate',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, default=(1, 1), srid=4326),
            preserve_default=False,
        ),
    ]
