# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-12 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=300)),
                ('associationFeaturesAvailable', models.CharField(max_length=1000)),
                ('associationFee', models.CharField(max_length=200, null=True)),
                ('associationFeeMQYN', models.CharField(max_length=200)),
                ('associationFeeIncludes', models.CharField(max_length=1000)),
                ('associationName', models.CharField(max_length=200)),
                ('associationPhone', models.CharField(max_length=200)),
                ('bathsFull', models.FloatField(blank=True, null=True)),
                ('bathsHalf', models.FloatField(blank=True, null=True)),
                ('bathsTotal', models.FloatField(blank=True, null=True)),
                ('bedroomsTotalPossibleNum', models.FloatField(blank=True, null=True)),
                ('bedsTotal', models.FloatField(blank=True, null=True)),
                ('buildingDescription', models.CharField(max_length=200)),
                ('closePrice', models.FloatField(blank=True, null=True)),
                ('communityName', models.CharField(max_length=300)),
                ('contructionDescription', models.CharField(max_length=300)),
                ('currentPrice', models.FloatField(blank=True, null=True)),
                ('directions', models.CharField(max_length=2000)),
                ('dryerIncluded', models.FloatField(blank=True, null=True)),
                ('dryerUltilities', models.CharField(max_length=200, null=True)),
                ('financingConsidered', models.CharField(max_length=300)),
                ('flooringDescription', models.CharField(max_length=300)),
                ('garageDescription', models.CharField(max_length=500)),
                ('houseFaces', models.CharField(max_length=100)),
                ('lastListPrice', models.FloatField(blank=True, null=True)),
                ('listAgentFullName', models.CharField(max_length=300)),
                ('listAgentMUI', models.CharField(max_length=200, null=True)),
                ('listOfficeName', models.CharField(max_length=300)),
                ('listOfficePhone', models.CharField(max_length=200)),
                ('listPrice', models.FloatField(blank=True, null=True)),
                ('mls', models.CharField(max_length=100)),
                ('mlsNumber', models.CharField(max_length=200, null=True)),
                ('matrixModifiedDT', models.DateTimeField()),
                ('matrixUniqueID', models.CharField(max_length=200, null=True)),
                ('photoCount', models.FloatField(blank=True, null=True)),
                ('postalCode', models.CharField(max_length=10)),
                ('propertyCondition', models.CharField(max_length=100)),
                ('propertySubType', models.CharField(max_length=100)),
                ('publicAddress', models.CharField(max_length=300)),
                ('publicRemarks', models.CharField(max_length=1000)),
                ('sellingAgentDirectWorkPhone', models.CharField(max_length=300)),
                ('sellingAgentFullName', models.CharField(max_length=400)),
                ('sellingAgentMUI', models.CharField(max_length=200, null=True)),
                ('sqftTotal', models.FloatField(blank=True, null=True)),
                ('streetName', models.CharField(max_length=200)),
                ('streetNumber', models.CharField(max_length=200, null=True)),
                ('subdivisionName', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('image', models.CharField(max_length=210)),
                ('summary', models.TextField()),
                ('keywords', models.TextField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='story',
            unique_together=set([('url',)]),
        ),
    ]
