# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-13 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20170613_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='interestedListing',
            field=models.CharField(default='null', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='lead',
            unique_together=set([]),
        ),
    ]
