# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-02 00:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20170530_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='listPrice',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
