# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-02 00:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_listing_listprice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='associationPhoneNumber',
            new_name='associationPhone',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='bedroomsTotalPossibleNumber',
            new_name='bedroomsTotalPossibleNum',
        ),
        migrations.AddField(
            model_name='listing',
            name='currentPrice',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='dryerUltilities',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='bathsTotal',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
