# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-02 01:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20170602_0134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='associationFee',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='listAgentMUI',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='matrixUniqueID',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='mlsNumber',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
