# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-02 02:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20170602_0159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='matrixModifiedDT',
            field=models.DateTimeField(),
        ),
    ]
