# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-02 02:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20170602_0233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='sellingAgentMUI',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
