# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-12 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20170602_0237'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('author', models.CharField(max_length=210)),
                ('url', models.CharField(max_length=210)),
                ('image', models.CharField(max_length=210)),
                ('summary', models.CharField(max_length=1000)),
                ('keywords', models.TextField()),
            ],
        ),
    ]
